name: to_do_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  animated_text_kit: ^4.2.2
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.22.1
  drift_flutter: ^0.2.4
  drift_sqflite: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  intl: ^0.18.0
  page_transition: ^2.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
dev_dependencies:
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null